apiVersion: v1
data:
  db-load-script.sql: "-- Create the database if it doesn't already exist\nCREATE
    DATABASE IF NOT EXISTS ecommerce;\n\n-- Use the created database\nUSE ecommerce;\n\n--
    Create the new user 'user1' with the specified password\nCREATE USER IF NOT EXISTS
    'user1'@'%' IDENTIFIED BY 'P@ssword123';\n\n-- Grant all privileges on the ecommerce_db
    to the new user\nGRANT ALL PRIVILEGES ON ecommerce.* TO 'user1'@'%';\n\n-- Apply
    the changes\nFLUSH PRIVILEGES;\n\n-- Create the users table\nCREATE TABLE IF NOT
    EXISTS users (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  username VARCHAR(100)
    NOT NULL,\n  email VARCHAR(100) NOT NULL,\n  password VARCHAR(255) NOT NULL,\n
    \ created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- Create the products
    table\nCREATE TABLE IF NOT EXISTS products (\n  id INT AUTO_INCREMENT PRIMARY
    KEY,\n  name VARCHAR(255) NOT NULL,\n  description TEXT,\n  price DECIMAL(10,2)
    NOT NULL,\n  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);\n\n-- Create the
    orders table\nCREATE TABLE IF NOT EXISTS orders (\n  id INT AUTO_INCREMENT PRIMARY
    KEY,\n  user_id INT NOT NULL,\n  total DECIMAL(10,2) NOT NULL,\n  created_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE
    CASCADE\n);\n\n-- Create the order_items table\nCREATE TABLE IF NOT EXISTS order_items
    (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  order_id INT NOT NULL,\n  product_id
    INT NOT NULL,\n  quantity INT NOT NULL,\n  price DECIMAL(10,2) NOT NULL,\n  created_at
    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n  FOREIGN KEY (order_id) REFERENCES orders(id)
    ON DELETE CASCADE,\n  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE
    CASCADE\n);\n\n-- Insert initial data (optional)\n-- Inserting a default admin
    user with hashed password\nINSERT INTO users (username, email, password) VALUES
    \n('admin', 'admin@example.com', MD5('password'));\n\n-- Insert sample products\nINSERT
    INTO products (name, description, price) VALUES \n('Daredevil', 'The Man Without
    Fear', 19.99),\n('Moon Knight', 'The Fist of Khonshu', 29.99),\n('Ghost Rider',
    'The Spirit of Vengeance', 39.99);\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mariadb-init-script
  namespace: e-comm
