apiVersion: v1
kind: Service
metadata:
  namespace: e-comm
  name: mysql-service
  labels:
    app: e-comm-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: e-comm-db
  clusterIP: None  # Headless service for direct pod-to-pod communication
